# Generated by Django 3.2 on 2022-12-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('vendor_code', models.CharField(max_length=150, unique=True, verbose_name='Артикул товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('status', models.CharField(choices=[('в наличии', 'В наличии'), ('под заказ', 'Под заказ'), ('ожидается поступление', 'Ожидается поступление'), ('нет в наличии', 'Нет в наличии'), ('не производится', 'Не производится')], max_length=150, verbose_name='Статус товара')),
                ('image', models.ImageField(upload_to='images/product/', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
